### ISSUE TITLE
Views - Should display only user's own posts

### ISSUE THREAD

**Issue by HannaAikas** [krisswiltshire30/acebook-fantastic-four#18]
Per feedback from Product Owner (Sophie - see slack message 11:37 13 Sept), once a user signs up / signs in, they should see a page that only has their **own posts**.
Currently they see all **posts from all users**.

**Comment by Stegosauruss** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(Edit) Users should view only their own posts.](https://trello.com/c/dApnRpDI/28-edit-users-should-view-only-their-own-posts)

**Comment by Stegosauruss** [comment]
Issue solved by pull request #22
